spring:
  application:
    name: challenge
  mvc:
      pathmatch:
            matching-strategy: ant-path-matcher
  
logging:
  level:
   root: DEBUG
   
    
config:
  user:
    secretKey: challengechallengechallengechallengechallengechallengechallengechallenge
    tokenExpirationAfterDays: 10
